### ISSUE TITLE
Avoiding use of static global variables

### ISSUE THREAD

**Issue by jonnor** [sipeed/TinyMaix#75]
Hi. I am working on porting TinyMaix to MicroPython, as part of the https://github.com/emlearn/emlearn-micropython project.

I am doing this a dynamic module in MicroPyhon, so it can be insalled at runtime. This environment has some restrictions. In particular, static global variables are not supported. Howevere non-static global variables are supported.
There are currently two uses of static globals in TinyMaix, in tm_layers.c:

```
static uint32_t k_oft[TM_MAX_KSIZE]; 
static mtype_t sbuf[TM_MAX_KCSIZE]; 
```
Here I needed to remove static to make the MicroPython linker happy. Once I did this, everything looks to compile and link fine :)

Now, I would like to make a fix for this that can go upstream in TinyMaix. I see two possible alternatives:

1. Replace static with TM_STATIC macro that can be adjusted from outside the library. Default to static, like it is now. But then it can be set to empty in the MicroPython environment.

2. Remove static completely, let these be non-static global variables always. In that case, the variables should get the `tm_` prefix, since they will be visible symbols also outside.

Would either of these be accepted? I can make PR with these changes, just need to know what you think is the best option.

**Comment by jonnor** [comment]
@Zepan do you have a recommendation for this?

**Comment by Zepan** [comment]
Hi, I think solution1 is better, it will keep the orignal usage for early user.
look forward to mpy's NN functions!
and you can send mail to zepan@sipeed.com if I missed github message

**Comment by jonnor** [comment]
Great, thank you for the feedback. I will try to make a patch next week or so :)
