### ISSUE TITLE
build: compilation errors with `-Werror` flag

### ISSUE THREAD

**Issue by windfallw** [sipeed/TinyMaix#8]
## Description
I'm trying to port this project to ESP32 using [Platformio-espressif32 5.1.1 (ESP-IDF 4.4.1) ](https://github.com/platformio/platform-espressif32), and I found that Platformio used [-Werror](https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html) flag for gcc compile which treat warning into an error.

`xtensa-esp32-elf-gcc -o .pio/build/esp32dev/src/main.o -c -Og -Wall -Werror=all -Wextra -Wno-error=deprecated-declarations -Wno-error=unused-but-set-variable -Wno-error=unused-function -Wno-error=unused-variable -Wno-frame-address -Wno-old-style-declaration -Wno-sign-compare -Wno-unused-parameter -fdata-sections -ffunction-sections......`

**Although it can be simplely add `build_unflags = -Werror=all` in `platformio.ini` to make the compilation successful, but I think it is better to fix these warnings for compatibility.**

https://community.platformio.org/t/disable-warning-errors/13280/2

## GCC output

[tm_model.c](https://github.com/sipeed/TinyMaix/blob/21a87290e8c46b66b9cf95372b699e443fa5eeff/src/tm_model.c#L98-L101)

```c
lib/TinyMaix/src/tm_model.c:98:23: error: pointer targets in assignment from 'uint8_t *' {aka 'unsigned char *'} to 'mtype_t *' {aka 'signed char *'} differ in signedness [-Werror=pointer-sign]
             _in.data  = mdl->buf + h->in_oft;
                       ^
lib/TinyMaix/src/tm_model.c:101:19: error: pointer targets in assignment from 'uint8_t *' {aka 'unsigned char *'} to 'mtype_t *' {aka 'signed char *'} differ in signedness [-Werror=pointer-sign]
         _out.data = mdl->buf + h->out_oft;
```

[tm_stat.c](https://github.com/sipeed/TinyMaix/blob/21a87290e8c46b66b9cf95372b699e443fa5eeff/src/tm_stat.c#L59-L60)

```c
lib/TinyMaix/src/tm_stat.c:59:61: error: format '%ld' expects argument of type 'long int', but argument 5 has type 'unsigned int' [-Werror=format=]
     printf("---\tInput    \t%3d,%3d,%3d\t-   \t0    \t0 \t%ld \t0\n",\
                                                           ~~^
                                                           %d
         idim[1],idim[2],idim[3], idim[1]*idim[2]*idim[3]*sizeof(mtype_t));
                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
lib/TinyMaix/src/tm_stat.c:113:64: error: format '%ld' expects argument of type 'long int', but argument 10 has type 'unsigned int' [-Werror=format=]
             printf("%03d\t%s      \t%3d,%3d,%3d\t%d\t%d\t%d\t%ld\t", layer_i, tml_str_tbl[h->type], \
                                                              ~~^
                                                              %d
```

[mnist.c](https://github.com/sipeed/TinyMaix/blob/21a87290e8c46b66b9cf95372b699e443fa5eeff/examples/mnist/main.c#L148-L149)

```c
src/mnist.c:144:25: error: missing braces around initializer [-Werror=missing-braces]
     tm_mat_t in_uint8 = {3, 28, 28, 1, (mtype_t *)mnist_pic};
                         ^
                                        {                   }
src/mnist.c:145:19: error: missing braces around initializer [-Werror=missing-braces]
     tm_mat_t in = {3, 28, 28, 1, NULL};
                   ^
```

## My solution

```c
_in.data = (mtype_t *)(mdl->buf + h->in_oft);
_out.data = (mtype_t *)(mdl->buf + h->out_oft);

printf("---\tInput    \t%3d,%3d,%3d\t-   \t0    \t0 \t%ld \t0\n",\
    idim[1],idim[2],idim[3], (long int)idim[1]*idim[2]*idim[3]*sizeof(mtype_t));
printf("%03d\t%s      \t%3d,%3d,%3d\t%d\t%d\t%d\t%ld\t", layer_i, tml_str_tbl[h->type], \
    h->out_dims[1], h->out_dims[2], h->out_dims[3], \
    h->in_oft, h->out_oft, h->size - tml_headsize_tbl[h->type], \
    (long int)memout*sizeof(mtype_t));

tm_mat_t in_uint8 = {3, 28, 28, 1, {(mtype_t *)mnist_pic}};
tm_mat_t in = {3, 28, 28, 1, {NULL}};
```

**Comment by Zepan** [comment]
hello, thank you for your report! just fixed it, please pull and try again~

**Comment by windfallw** [comment]
> hello, thank you for your report! just fixed it, please pull and try again~

Hi, I have tried the newest repo, now it works with platformio without unflag `-Werror=all`.
just with some unused variable and multi-character character constant warnings, but that doesn't matter
